language: cpp
sudo: required
dist: trusty
compiler:
- clang
os:
- linux
- osx
before_install:
- echo $LANG
- echo $LC_ALL
- if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install libssl-dev unixodbc-dev libsqliteodbc gdb valgrind ; fi
- if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install openssl unixodbc sqliteodbc; fi
- if [[ -f /etc/odbc.ini ]]; then cat /etc/odbc.ini; fi
- if [[ -f /etc/odbc.ini ]]; then cat /etc/odbc.ini; fi
- if [[ -f /usr/local/etc/odbc.ini ]]; then cat /usr/local/etc/odbc.ini; fi
- if [[ -f /etc/odbcinst.ini ]]; then cat /etc/odbcinst.ini; fi
- if [[ -f /usr/local/etc/odbcinst.ini ]]; then cat /usr/local/etc/odbcinst.ini; fi
- odbcinst -j || true
- >-
  odbcinst -j | grep -E '(DRIVERS)|(DATA SOURCES)' | sed 's/.*: //' | xargs -t cat || true
- ulimit -c
- ulimit -a -S
- ulimit -a -H
- if [ $TRAVIS_OS_NAME == linux ]; then cat /proc/sys/kernel/core_pattern; fi
install:
- ulimit -c unlimited -S
- if [ $TRAVIS_OS_NAME == linux ]; then sudo sh -c 'echo "core.%e.%p.%s.%t" > /proc/sys/kernel/core_pattern'; fi
- ulimit -c
- ulimit -a -S
- ulimit -a -H
- if [ $TRAVIS_OS_NAME == linux ]; then cat /proc/sys/kernel/core_pattern; fi
before_script:
- mkdir build
- cd build
script:
- if [ $TRAVIS_OS_NAME == osx ]; then export CMAKE_OPTS="-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/ -DAUTH_TEST_ODBC_SQLITE_DRIVER=/usr/local/lib/libsqlite3odbc.dylib -DODBC_DIR=/usr/local/"; fi
- cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_SHARED_LIBS=TRUE $CMAKE_OPTS
- cmake --build . --target package --config RelWithDebInfo
- if [ $TRAVIS_OS_NAME == linux ]; then valgrind --trace-children=yes ctest -VV ; else ctest -VV ; fi
after_failure:
- ls -l
- tail -n +1 log/* || true
- if [ $TRAVIS_OS_NAME == linux ]; then for i in $(find ./ -maxdepth 1 -name 'core*' -print); do echo "Core $i" && file "$i" && gdb "$(file "$i" | sed -r "s/.*from '([^ ']+)[ '].*/\1/")" "$i" -ex "thread apply all bt" -ex "set pagination 0" -batch; done; fi
deploy:
  provider: releases
  api_key:
    secure: WJV1VnKFtrg+rwA26yFxXHxIiol2ITzcOWrXr8PiiRTNyAwjXy3X6vb7XxvE/DGqus73GaES566fQw/iTSZmOgJ+FUig5grbuiMNtTQwkQ23o8+YRoR37yyZtVJPmYBITdNa7ZIOLP6L+4MyLqOikpUhXYpMTgTmiH2jP17AeXyw2j2lp7qd2Nd2Iy/2Vpm8X26gaE4uFsw94HtDOcCwVV/CuDz8MRkampVf7AvFA4VTh8/rS2GWkXeuOeY4AhLgfUDCAkWknBzuWUO90utudHTusdwSyiJ/q9SM3mAyP7LEhZPCb//6QaCdFN40Cg5t8s5mjBhEpw7LSDnyDyEj4Xi2A1SVOIBrFhnKz2sTLOxnS4SxSlSNeQrxTmdFv0WDw4GXFvj30cOF5U+S4jNoCS+1AUO16M6UPp6fjYg64tGCNbgQIH4SwfcgjISurlWOZtLGiSd8QJ74daY1zBVBFbewI8xEtvWbKBerFJQYe5zWI1lxczNrF/nVLtQ3vkTPZdOvljAlC7aRaq81OzsYs5/YYLaFKrhsAzX8wrAcb2opgAFhoip5u9HkRE2O+Q/cQ8IcUSm2SoPV1MYvIfGFH7y1j5pIZTto9xGQaSllGfrFVzFG/n4Vt9Leq164cRito8CUvqgLQUTd8mOy75RUu/9pxh6z/gDeN9NzTWFIk3c=
  file:
    - rzemu-4.1-Linux-x86_64-binaries.zip
    - rzemu-4.1-Linux-x86_64-symbols.zip
  skip_cleanup: true
  on:
    tags: true
