language: cpp
sudo: required
dist: trusty
compiler:
- clang
os:
- linux
- osx
before_install:
- echo $LANG
- echo $LC_ALL
- if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository ppa:jonathonf/backports -y ; fi
- if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install libssl-dev unixodbc-dev libsqliteodbc gdb valgrind ; fi
- if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install openssl unixodbc sqliteodbc; fi
- if [[ -f /etc/odbc.ini ]]; then cat /etc/odbc.ini; fi
- if [[ -f /etc/odbc.ini ]]; then cat /etc/odbc.ini; fi
- if [[ -f /usr/local/etc/odbc.ini ]]; then cat /usr/local/etc/odbc.ini; fi
- if [[ -f /etc/odbcinst.ini ]]; then cat /etc/odbcinst.ini; fi
- if [[ -f /usr/local/etc/odbcinst.ini ]]; then cat /usr/local/etc/odbcinst.ini; fi
- odbcinst -j || true
- >-
  odbcinst -j | grep -E '(DRIVERS)|(DATA SOURCES)' | sed 's/.*: //' | xargs -t cat || true
- ulimit -c
- ulimit -a -S
- ulimit -a -H
- if [ $TRAVIS_OS_NAME == linux ]; then cat /proc/sys/kernel/core_pattern; fi
install:
- ulimit -c unlimited -S
- if [ $TRAVIS_OS_NAME == linux ]; then sudo sh -c 'echo "core.%e.%p.%s.%t" > /proc/sys/kernel/core_pattern'; fi
- ulimit -c
- ulimit -a -S
- ulimit -a -H
- if [ $TRAVIS_OS_NAME == linux ]; then cat /proc/sys/kernel/core_pattern; fi
before_script:
- mkdir build
- cd build
script:
- if [ $TRAVIS_OS_NAME == osx ]; then export CMAKE_OPTS="-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/ -DAUTH_TEST_ODBC_SQLITE_DRIVER=/usr/local/lib/libsqlite3odbc.dylib -DODBC_DIR=/usr/local/"; fi
- cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_SHARED_LIBS=FALSE $CMAKE_OPTS
- cmake --build . --target package --config RelWithDebInfo
- if [ $TRAVIS_OS_NAME == linux ]; then valgrind --trace-children=yes ctest -VV ; else ctest -VV ; fi
after_failure:
- ls -l
- tail -n +1 log/* || true
- if [ $TRAVIS_OS_NAME == linux ]; then for i in $(find ./ -maxdepth 1 -name 'core*' -print); do echo "Core $i" && file "$i" && gdb "$(file "$i" | sed -r "s/.*from '([^ ']+)[ '].*/\1/")" "$i" -ex "thread apply all bt" -ex "set pagination 0" -batch; done; fi

