if(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
    set(LIBUV_OS_WIN 1)
	message("LIBUV_OS_WIN")
elseif(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    if(ANDROID)
        set(LIBUV_OS_ANDROID 1)
	    message("LIBUV_OS_ANDROID")
    else()
        set(LIBUV_OS_LINUX 1)
		message("LIBUV_OS_LINUX")
    endif()
elseif(${CMAKE_SYSTEM_NAME} MATCHES "FreeBSD")
    set(LIBUV_OS_FREEBSD 1)
	message("LIBUV_OS_FREEBSD")
elseif(${CMAKE_SYSTEM_NAME} MATCHES "OpenBSD")
    set(LIBUV_OS_OPENBSD 1)
	message("LIBUV_OS_OPENBSD")
elseif(${CMAKE_SYSTEM_NAME} MATCHES "NetBSD")
    set(LIBUV_OS_NETBSD 1)
	message("LIBUV_OS_NETBSD")
elseif(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    set(LIBUV_OS_MAC 1)
	message("LIBUV_OS_MAC")
elseif(${CMAKE_SYSTEM_NAME} MATCHES "Android")
    set(LIBUV_OS_ANDROID 1)
	message("LIBUV_OS_ANDROID")
elseif(${CMAKE_SYSTEM_NAME} MATCHES "AIX")
    set(LIBUV_OS_AIX 1)
	message("LIBUV_OS_AIX")
elseif(${CMAKE_SYSTEM_NAME} MATCHES "SunOS")
    set(LIBUV_OS_SOLARIS 1)
	message("LIBUV_OS_SOLARIS")
else()
    message(FATAL_ERROR "Unsupported operating system")
    return()
endif()
